version: "3.9"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - redis 
    environment:
      DB_USER: root
      DB_NAME: chat_system
      DB_PASSWORD: password
      DB_HOST: db
      ELASTICSEARCH_URL: elasticsearch
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: chat_system
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data
  
  sidekiq:
    depends_on:
      - redis
    links:
      - db
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: development

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "discovery.type=single-node"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker_data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  db:
  redis:
  elasticsearch:
  sidekiq:
